// 365 catalog - chunk 1: DevTools, CLI tools, Automation
module.exports = [
  { t: "CommitLens", c: "DevTools", b: "A local git history browser that surfaces commit patterns, author velocity and hot files from any repository.", g: "react-app" },
  { t: "DependaWarden", c: "DevTools", b: "Scans a project manifest and flags outdated, deprecated or vulnerable dependencies before you ship.", g: "python-cli" },
  { t: "DotEnvDoctor", c: "DevTools", b: "Validates .env files against documented keys, catches missing or extra variables and keeps secrets out of logs.", g: "python-cli" },
  { t: "SmokeSweep", c: "DevTools", b: "A fast smoke-test runner that boots your app and checks the critical paths in under a minute.", g: "node-api" },
  { t: "TrailNest", c: "DevTools", b: "Stores and organizes command-line history with searchable tags, so you never retype a long command.", g: "python-cli" },
  { t: "PortPilot", c: "DevTools", b: "Lists processes holding a port, shows connection details and lets you free a busy port quickly.", g: "python-cli" },
  { t: "SnippetVault", c: "DevTools", b: "A local snippet manager with language-aware search and clipboard-ready insertion.", g: "webapp" },
  { t: "FileFingerprint", c: "DevTools", b: "Computes hashes and reports duplicate files across a folder tree so you can reclaim disk space.", g: "python-cli" },
  { t: "EnvDiff", c: "DevTools", b: "Compares two environment or config files and reports what changed, added or disappeared.", g: "python-cli" },
  { t: "SchemaSpyglass", c: "DevTools", b: "Renders a readable map of a JSON schema with required fields, types and nesting depth.", g: "python-cli" },
  { t: "LogStitch", c: "DevTools", b: "Merges and interleaves log files by timestamp to rebuild a single timeline of events.", g: "python-pipeline" },
  { t: "SecretsScanner", c: "DevTools", b: "Scans a repository for accidental credentials and API keys before they get committed.", g: "python-cli" },
  { t: "SwaggerLint", c: "DevTools", b: "Lints OpenAPI documents for broken references, missing responses and naming inconsistencies.", g: "python-cli" },
  { t: "ReleaseNote", c: "DevTools", b: "Builds a release notes draft from merged commits and tag history with zero manual typing.", g: "python-cli" },
  { t: "GitGuard", c: "DevTools", b: "Runs pre-push checks against a repo and blocks commits that contain suspicious patterns.", g: "python-cli" },
  { t: "TaskRanger", c: "DevTools", b: "A terminal task board with priority lanes and a plain-text storage format you can grep.", g: "python-cli" },
  { t: "BundlePeek", c: "DevTools", b: "Explains what makes a JS bundle heavy by walking the module graph and reporting top contributors.", g: "node-api" },
  { t: "GrepSeeker", c: "DevTools", b: "A parallel grep frontend that highlights matches, groups results by file and pipes into your editor.", g: "python-cli" },
  { t: "MonorepoSplit", c: "DevTools", b: "Splits a monorepo into standalone repositories while preserving each folder's commit history.", g: "python-script" },
  { t: "BuildBoard", c: "DevTools", b: "A local dashboard that watches your build outputs and alerts when a step regresses.", g: "webapp" },
  { t: "CLangStats", c: "DevTools", b: "Counts lines, comments and blanks per language in a codebase and exports a breakdown.", g: "python-cli" },
  { t: "PRSummarizer", c: "DevTools", b: "Reads a pull request diff and prints a plain summary of the files and functions touched.", g: "python-cli" },
  { t: "DependencyTree", c: "DevTools", b: "Renders the dependency graph of a Python or Node project as an ASCII tree with sizes.", g: "python-cli" },
  { t: "CacheTrove", c: "DevTools", b: "A key-value cache for scripts with TTL support and a tiny JSON backend.", g: "python-cli" },
  { t: "EditorKit", c: "DevTools", b: "A set of small editor helper scripts for formatting, encoding and reflowing text in bulk.", g: "python-script" },
  { t: "SemverHelper", c: "DevTools", b: "Handles version bumps, changelog updates and tags so releases stay consistent.", g: "python-cli" },
  { t: "DocBuilder", c: "DevTools", b: "Generates a static documentation site from markdown files with a sidebar and search.", g: "static-site" },
  { t: "WatchGuard", c: "DevTools", b: "Runs a command whenever files change, with debounce and per-extension rules.", g: "python-cli" },
  { t: "EnvDoctor", c: "DevTools", b: "Detects missing system tools and environment quirks that break local development setups.", g: "python-cli" },
  { t: "SQLFormatter", c: "DevTools", b: "Pretty-prints SQL statements with aligned keywords and configurable indentation.", g: "python-cli" },
  { t: "DiffVisualizer", c: "DevTools", b: "Renders unified diffs in the terminal with color coding and word-level highlighting.", g: "python-cli" },
  { t: "ConfigDoctor", c: "DevTools", b: "Checks config files for typos, duplicate keys and values that fall outside expected ranges.", g: "python-cli" },
  { t: "ApiSpy", c: "DevTools", b: "Intercepts and records HTTP requests made by your local app for debugging and replay.", g: "node-api" },
  { t: "DockWatch", c: "DevTools", b: "Tails container logs across a compose project with filters and highlighted error lines.", g: "python-cli" },
  { t: "i18nSync", c: "DevTools", b: "Keeps translation files in sync by reporting missing or unused keys across locales.", g: "python-cli" },
  { t: "FlakeHunt", c: "DevTools", b: "Re-runs flaky test patterns to isolate nondeterministic failures and prints a report.", g: "python-script" },
  { t: "TidyReaper", c: "DevTools", b: "Finds and removes stale build artifacts, temp folders and large files from a project.", g: "python-cli" },
  { t: "ChangelogCraft", c: "DevTools", b: "Maintains a changelog file from conventional commit messages grouped by type.", g: "python-cli" },
  { t: "HealthCheckKit", c: "DevTools", b: "A set of health-check probes for common services with a friendly status summary.", g: "python-cli" },
  { t: "BenchScope", c: "DevTools", b: "Runs micro-benchmarks for pure functions and reports variance across runs.", g: "python-cli" },
  { t: "MkVault", c: "DevTools", b: "A filesystem-based notes vault with daily pages, backlinks and a simple search index.", g: "webapp" },
  { t: "QuickSort", c: "CLI", b: "A portable file organizer that sorts downloads by type, date or extension rules.", g: "python-cli" },
  { t: "BulkRenamePro", c: "CLI", b: "Renames many files using patterns, find-and-replace and number sequences safely.", g: "python-cli" },
  { t: "JSONFiddle", c: "CLI", b: "Formats, minifies, diffs and queries JSON from the command line without leaving the terminal.", g: "python-cli" },
  { t: "CSVCompanion", c: "CLI", b: "Inspects CSV files, prints column stats and filters rows with a small query language.", g: "python-cli" },
  { t: "HexDumpDeluxe", c: "CLI", b: "Renders files as hex with an ASCII column, offsets and searchable patterns.", g: "python-cli" },
  { t: "TimerStack", c: "CLI", b: "A terminal stopwatch and countdown stack for pomodoros and batch workflows.", g: "python-cli" },
  { t: "ClipMate", c: "CLI", b: "Keeps a history of clipboard entries and lets you paste any previous copy from the terminal.", g: "python-cli" },
  { t: "SSHQuick", c: "CLI", b: "Manages a curated list of SSH hosts with fuzzy selection and quick connect.", g: "python-cli" },
  { t: "ImageTiny", c: "CLI", b: "Shrinks image files in a folder with quality settings and before/after size reports.", g: "python-cli" },
  { t: "MarkdownBoard", c: "CLI", b: "Turns a markdown checklist file into a terminal progress board with live totals.", g: "python-cli" },
  { t: "YamlTouch", c: "CLI", b: "Validates, pretty-prints and patches YAML files from the command line.", g: "python-cli" },
  { t: "Ziplock", c: "CLI", b: "Packs and encrypts folders into single archives with password support.", g: "python-cli" },
  { t: "TextTransmute", c: "CLI", b: "Converts text between cases, encodings and formats using a single piped command.", g: "python-cli" },
  { t: "NetSniff", c: "CLI", b: "Shows listening ports, active connections and per-process network usage.", g: "go-tool" },
  { t: "ColorPilot", c: "CLI", b: "Converts, mixes and previews colors in the terminal with export to code palettes.", g: "python-cli" },
  { t: "CrontabBuddy", c: "CLI", b: "Explains cron expressions in plain words and generates next-run schedules.", g: "go-tool" },
  { t: "FileWatchdog", c: "CLI", b: "Watches a directory and alerts when files appear, change or exceed a size limit.", g: "python-cli" },
  { t: "PermPrint", c: "CLI", b: "Decodes file permission modes and prints human-readable explanations for each.", g: "go-tool" },
  { t: "DotfileSync", c: "CLI", b: "Tracks dotfiles in a git repo and links them into place across machines.", g: "python-cli" },
  { t: "CookieJar", c: "CLI", b: "Stores and replays HTTP cookies for API sessions right from the terminal.", g: "python-cli" },
  { t: "FuzzyFind", c: "CLI", b: "A fuzzy file finder with preview, history and instant open in your editor.", g: "python-cli" },
  { t: "TableDraw", c: "CLI", b: "Renders JSON or CSV data as aligned terminal tables with customizable columns.", g: "python-cli" },
  { t: "CleanUp", c: "CLI", b: "Safely deletes old log files, temp folders and caches with a dry-run preview.", g: "python-cli" },
  { t: "UnitSwap", c: "CLI", b: "Converts between units of length, weight, speed and temperature in a calculator style.", g: "python-cli" },
  { t: "BookmarkHost", c: "CLI", b: "Manages a searchable list of links with tags and quick open in the browser.", g: "chrome-extension" },
  { t: "ShellPrompt", c: "CLI", b: "A lightweight prompt helper that shows git status and context in your terminal.", g: "python-script" },
  { t: "RSSPrune", c: "Automation", b: "Fetches feeds, filters unread items and exports a clean digest to a file.", g: "python-script" },
  { t: "FolderWatcher", c: "Automation", b: "Watches a folder and runs configured actions when new files arrive.", g: "python-cli" },
  { t: "BackupChain", c: "Automation", b: "Runs scheduled folder backups with rotation, compression and integrity checks.", g: "python-cli" },
  { t: "MailDigest", c: "Automation", b: "Aggregates daily notifications into a single readable summary file.", g: "python-pipeline" },
  { t: "ScreenGrabber", c: "Automation", b: "Captures screenshots of a page list on a schedule and stores them with timestamps.", g: "python-cli" },
  { t: "RenameByDate", c: "Automation", b: "Renames photo and document files using their creation dates and custom templates.", g: "python-script" },
  { t: "ReportStitcher", c: "Automation", b: "Combines daily report fragments from many folders into one dated document.", g: "python-pipeline" },
  { t: "CronRunner", c: "Automation", b: "A self-contained scheduler that runs jobs from a simple YAML file with logging.", g: "python-cli" },
  { t: "TemplateFiller", c: "Automation", b: "Fills document templates from a spreadsheet and writes one file per row.", g: "python-script" },
  { t: "WebPinger", c: "Automation", b: "Checks a list of URLs on an interval and logs outages with response times.", g: "python-cli" },
  { t: "FileOrganizer", c: "Automation", b: "Auto-sorts an inbox folder into structured subfolders based on rules you define.", g: "python-cli" },
  { t: "InvoiceBot", c: "Automation", b: "Generates simple invoice files from a plain-text work log and numbers them sequentially.", g: "python-script" },
  { t: "UpdateChaser", c: "Automation", b: "Polls package registries and reports when tracked tools release new versions.", g: "python-cli" },
  { t: "ArchiveRoller", c: "Automation", b: "Rolls old folders into dated archives and keeps only the most recent N copies.", g: "python-cli" },
  { t: "FormSubmitter", c: "Automation", b: "Replays saved HTTP form submissions with configurable values and stores responses.", g: "python-cli" },
  { t: "DownloadSweeper", c: "Automation", b: "Cleans a downloads folder daily by grouping files and moving them to destinations.", g: "python-cli" },
  { t: "MeetingNotes", c: "Automation", b: "Turns a plain notes file into a formatted summary with action items extracted.", g: "python-pipeline" },
  { t: "TaskAlerts", c: "Automation", b: "Watches task lists and sends desktop-style reminders when deadlines approach.", g: "python-cli" },
  { t: "LogRotator", c: "Automation", b: "Rotates application logs by size or date and compresses the old ones.", g: "python-cli" },
  { t: "GitSync", c: "Automation", b: "Auto-commits and pushes a watched folder on an interval with grouped messages.", g: "python-script" },
  { t: "PhotoSorter", c: "Automation", b: "Sorts images into year and month folders based on file metadata.", g: "python-cli" },
  { t: "ConfigSweep", c: "Automation", b: "Backs up and version-controls application config files before upgrades.", g: "python-script" },
  { t: "DiskAlerter", c: "Automation", b: "Monitors disk usage and warns when thresholds are crossed on watched paths.", g: "python-cli" },
  { t: "SeedFiller", c: "Automation", b: "Generates realistic test data from a schema and writes it to JSON or CSV.", g: "python-cli" },
  { t: "RefactorMap", c: "DevTools", b: "Visualizes code coupling between modules and flags safe refactor candidates.", g: "python-cli" },
  { t: "HotSwap", c: "DevTools", b: "Swaps config sets between environments with a backup and rollback step.", g: "python-cli" },
  { t: "SnippetBench", c: "DevTools", b: "Benchmarks two code snippets head to head and prints a fair comparison.", g: "python-cli" },
  { t: "ArchiveList", c: "CLI", b: "Lists archive contents and inspects entries without extracting anything.", g: "python-cli" },
  { t: "PwdGen", c: "CLI", b: "Generates random passwords with a strength meter and copy-ready output.", g: "go-tool" },
  { t: "GrepIt", c: "CLI", b: "Searches files with context, color highlighting and exclusion filters.", g: "python-cli" },
  { t: "ScreenshotDiff", c: "Automation", b: "Captures page screenshots over time and reports visual changes.", g: "python-cli" },
  { t: "FileRoute", c: "Automation", b: "Routes incoming files to different handlers based on name patterns.", g: "python-cli" },
  { t: "TaskScheduler", c: "Automation", b: "A visual scheduler for repeating local jobs with a status board.", g: "webapp" }
];
