// 365 catalog - chunk 2: Web3, Web apps, API
module.exports = [
  { t: "TokenVault", c: "Web3", b: "A local wallet-key vault that stores addresses and encrypted keys behind a passphrase.", g: "python-cli" },
  { t: "GasLighter", c: "Web3", b: "Estimates and tracks gas costs for transactions and prints fee breakdowns.", g: "python-cli" },
  { t: "BlockFollower", c: "Web3", b: "Tails new blocks and prints transactions matching configurable filter rules.", g: "python-cli" },
  { t: "ContractInspect", c: "Web3", b: "Decodes function selectors and event topics from contract ABIs and call data.", g: "python-cli" },
  { t: "WalletTracker", c: "Web3", b: "Monitors a set of wallet addresses and logs balance changes over time.", g: "python-cli" },
  { t: "NFTGallery", c: "Web3", b: "Fetches token metadata for a collection and renders a simple offline gallery.", g: "webapp" },
  { t: "TokenSwapCalc", c: "Web3", b: "Estimates token swap rates and slippage for a given input amount.", g: "python-cli" },
  { t: "ChainPing", c: "Web3", b: "Checks the status and latency of multiple blockchains from one command.", g: "python-cli" },
  { t: "SignatureCheck", c: "Web3", b: "Verifies message and transaction signatures against a public key.", g: "python-cli" },
  { t: "BlockExplorer", c: "Web3", b: "A readable local explorer for a chain index that searches by hash or address.", g: "webapp" },
  { t: "LiquidityWatch", c: "Web3", b: "Tracks liquidity pool changes for a pair and alerts on large moves.", g: "python-cli" },
  { t: "MintMeter", c: "Web3", b: "Counts mints per block range and prints distribution statistics.", g: "python-pipeline" },
  { t: "StakePlanner", c: "Web3", b: "Projects staking rewards across time horizons with APY assumptions.", g: "python-cli" },
  { t: "TxFeeEstimator", c: "Web3", b: "Samples recent fees and estimates the cost of a transaction under urgency tiers.", g: "python-cli" },
  { t: "AddressBook", c: "Web3", b: "A local book of labeled addresses with tags and quick lookup by name.", g: "python-cli" },
  { t: "Web3Scaffold", c: "Web3", b: "Generates a boilerplate dApp frontend wired to a provider and a sample contract.", g: "react-app" },
  { t: "TokenTransferLog", c: "Web3", b: "Summarizes token transfers from an address across a date range.", g: "python-pipeline" },
  { t: "DeployTracker", c: "Web3", b: "Logs contract deployment events and verifies the resulting addresses.", g: "python-cli" },
  { t: "FeeComparer", c: "Web3", b: "Compares transaction costs across chains for the same operation.", g: "python-cli" },
  { t: "AirdropClaimer", c: "Web3", b: "Watches for claimable balances and prepares batch claim reports.", g: "python-cli" },
  { t: "MempoolPeek", c: "Web3", b: "Shows pending transactions with gas prices from a mempool feed.", g: "python-cli" },
  { t: "RecoveryKit", c: "Web3", b: "Guides restoring wallets from seed phrases and verifies derived addresses.", g: "webapp" },
  { t: "StableCoinCalc", c: "Web3", b: "Converts between fiat and stablecoin amounts with live rate input.", g: "python-cli" },
  { t: "BridgeWatch", c: "Web3", b: "Tracks bridge transactions and reports confirmation progress across chains.", g: "python-cli" },
  { t: "ValidatorRank", c: "Web3", b: "Compares validator performance metrics and prints a sorted table.", g: "python-cli" },
  { t: "BudgetBoard", c: "Web apps", b: "A simple monthly budget board that categorizes expenses and shows remaining per category.", g: "webapp" },
  { t: "RecipeBox", c: "Web apps", b: "A personal recipe collection with ingredient lists, tags and quick search.", g: "webapp" },
  { t: "HabitHarbor", c: "Web apps", b: "Tracks daily habits with streaks, weekly grids and gentle reminders.", g: "react-app" },
  { t: "BookShelf", c: "Web apps", b: "A reading tracker with a bookshelf view, statuses and reading notes.", g: "webapp" },
  { t: "PlaylistBuilder", c: "Web apps", b: "Curates a playlist from a mood selection and a local track library.", g: "webapp" },
  { t: "ExpenseSplit", c: "Web apps", b: "Splits group expenses fairly and prints who owes whom.", g: "webapp" },
  { t: "StudyPlanner", c: "Web apps", b: "Builds a study timetable from subjects, deadlines and available hours.", g: "react-app" },
  { t: "MealPlanner", c: "Web apps", b: "Plans a week of meals from a recipe list and generates a shopping list.", g: "webapp" },
  { t: "TripPlanner", c: "Web apps", b: "Organizes a trip itinerary day by day with notes and packing lists.", g: "react-app" },
  { t: "WeightLog", c: "Web apps", b: "Logs daily measurements and renders trends with a rolling average line.", g: "react-app" },
  { t: "SleepJournal", c: "Web apps", b: "Records sleep quality and duration and prints weekly summaries.", g: "webapp" },
  { t: "WaterReminder", c: "Web apps", b: "Tracks water intake across the day with a goal bar and history.", g: "webapp" },
  { t: "FitnessLog", c: "Web apps", b: "Logs workouts, sets and reps and shows volume trends per exercise.", g: "react-app" },
  { t: "SavingsTracker", c: "Web apps", b: "Projects savings growth toward goals with monthly contribution inputs.", g: "webapp" },
  { t: "MovieDiary", c: "Web apps", b: "Keeps a watchlist and diary of films with ratings and short reviews.", g: "webapp" },
  { t: "BoardGameScore", c: "Web apps", b: "Scores board game sessions across players and keeps a running winner list.", g: "webapp" },
  { t: "CafeFinder", c: "Web apps", b: "A personal list of cafes with notes on wifi, seating and coffee quality.", g: "webapp" },
  { t: "PetHealth", c: "Web apps", b: "Tracks pet feeding, medication and vet visits on a simple calendar.", g: "webapp" },
  { t: "GiftPlanner", c: "Web apps", b: "Tracks gift ideas, budgets and purchase statuses by occasion.", g: "webapp" },
  { t: "ChoreWheel", c: "Web apps", b: "Rotates household chores across members and logs who did what when.", g: "webapp" },
  { t: "RoutineBuilder", c: "Web apps", b: "Designs a daily routine from a list of activities with time blocks.", g: "react-app" },
  { t: "Wishlist", c: "Web apps", b: "Maintains a wishlist with prices, links and prioritization.", g: "webapp" },
  { t: "PlantCare", c: "Web apps", b: "Tracks watering schedules for houseplants and reminds when due.", g: "webapp" },
  { t: "EventPlanner", c: "Web apps", b: "Plans an event with tasks, budgets and a guest countdown.", g: "react-app" },
  { t: "JobTracker", c: "Web apps", b: "Tracks job applications, follow-ups and interview stages in one board.", g: "react-app" },
  { t: "NoteNest", c: "Web apps", b: "A plain-text notes app with folders, search and a distraction-free editor.", g: "webapp" },
  { t: "QuoteWall", c: "Web apps", b: "Displays a rotating wall of saved quotes with tags and favorites.", g: "webapp" },
  { t: "PhotoAlbum", c: "Web apps", b: "Organizes photos into albums with captions and a simple slideshow.", g: "webapp" },
  { t: "IdeaFountain", c: "Web apps", b: "Captures and reviews random ideas with periodic prompts to revisit them.", g: "react-app" },
  { t: "SpotifyClone", c: "Web apps", b: "A music player UI with a track queue and an equalizer visualizer.", g: "react-app" },
  { t: "RESTClient", c: "API", b: "Builds and replays HTTP requests with headers, body and saved collections.", g: "node-api" },
  { t: "RateLimitProbe", c: "API", b: "Tests an API's rate limits and reports the observed thresholds.", g: "python-cli" },
  { t: "WebhookTester", c: "API", b: "Receives webhook deliveries locally and shows the parsed payloads.", g: "node-api" },
  { t: "APIHealthWatch", c: "API", b: "Polls API endpoints on a schedule and logs latency, status and downtime.", g: "node-api" },
  { t: "QueryBuilder", c: "API", b: "Builds and tests complex query strings from a form-like interface.", g: "webapp" },
  { t: "EndpointMapper", c: "API", b: "Walks an OpenAPI document and prints every endpoint with methods and params.", g: "python-cli" },
  { t: "ProxyTunnel", c: "API", b: "Exposes a local service through a tiny tunnel for webhook testing.", g: "node-api" },
  { t: "CacheProxy", c: "API", b: "Caches upstream API responses with TTL and invalidation rules.", g: "node-api" },
  { t: "PaginationTest", c: "API", b: "Drives paginated endpoints and verifies page consistency and totals.", g: "python-cli" },
  { t: "AuthFlowLab", c: "API", b: "Walks through OAuth and token exchange flows against a sandbox server.", g: "python-cli" },
  { t: "JSONSchemaGen", c: "API", b: "Generates JSON Schema drafts from example payloads with sensible guesses.", g: "python-cli" },
  { t: "MockAPI", c: "API", b: "Serves configurable mock responses for endpoints defined in a YAML file.", g: "node-api" },
  { t: "HeaderDoctor", c: "API", b: "Inspects HTTP headers on a response and flags missing security headers.", g: "python-cli" },
  { t: "RetryLab", c: "API", b: "Simulates flaky responses to tune retry and backoff strategies.", g: "node-api" },
  { t: "FileUploadProbe", c: "API", b: "Tests file upload endpoints with size, type and parallel variants.", g: "python-cli" },
  { t: "GraphQLExplorer", c: "API", b: "Runs GraphQL queries against an endpoint and formats the results.", g: "webapp" },
  { t: "ResponseCompare", c: "API", b: "Diffs two API responses field by field and prints the changes.", g: "python-cli" },
  { t: "TokenRefresher", c: "API", b: "Manages access and refresh tokens with automatic renewal and expiry logs.", g: "python-cli" },
  { t: "WebhookFwd", c: "API", b: "Forwards webhook payloads to multiple destinations with header rewriting.", g: "node-api" },
  { t: "APIDocumenter", c: "API", b: "Generates markdown API docs from a captured request log.", g: "python-pipeline" }
];
