// 365 catalog - chunk 4: Productivity, Libraries, Design/UI, System, Sites, Bots, DevOps
module.exports = [
  { t: "FocusTimer", c: "Productivity", b: "A pomodoro timer with session goals, break reminders and a daily total.", g: "chrome-extension" },
  { t: "DailyLog", c: "Productivity", b: "A daily journal with prompts, tags and a searchable history.", g: "webapp" },
  { t: "TodoMatrix", c: "Productivity", b: "An Eisenhower matrix that sorts tasks by urgency and importance.", g: "react-app" },
  { t: "GoalTracker", c: "Productivity", b: "Tracks goals with measurable milestones and progress bars.", g: "webapp" },
  { t: "ReadingList", c: "Productivity", b: "A reading queue with priorities, notes and finished dates.", g: "webapp" },
  { t: "TimeLogger", c: "Productivity", b: "Logs time spent on activities and prints weekly breakdowns.", g: "python-cli" },
  { t: "StickyBoard", c: "Productivity", b: "A kanban board for ideas and tasks stored as local markdown files.", g: "webapp" },
  { t: "HabitStreak", c: "Productivity", b: "Tracks habit streaks with heatmap-style history and resets.", g: "chrome-extension" },
  { t: "FocusScore", c: "Productivity", b: "Scores your day's focus based on completed tasks and distraction blocks.", g: "webapp" },
  { t: "MeetingAgenda", c: "Productivity", b: "Builds meeting agendas from topics with timeboxing and outcomes.", g: "webapp" },
  { t: "InboxZero", c: "Productivity", b: "Tracks email-like inbox counts and rewards clearing the queue.", g: "chrome-extension" },
  { t: "PomodoroBoard", c: "Productivity", b: "A visual board of pomodoro sessions per task for the week.", g: "react-app" },
  { t: "GoalDash", c: "Productivity", b: "A personal dashboard showing goals, streaks and weekly stats at a glance.", g: "react-app" },
  { t: "IdeaVault", c: "Productivity", b: "A searchable idea vault with quick capture and random revisit.", g: "webapp" },
  { t: "PlanWeek", c: "Productivity", b: "Plans the week from a backlog with time estimates and a done list.", g: "webapp" },
  { t: "TimerLog", c: "Productivity", b: "Logs timed work sessions with project tags and total durations.", g: "python-cli" },
  { t: "NotesExtract", c: "Productivity", b: "Extracts tasks and dates from freeform notes into a checklist.", g: "python-pipeline" },
  { t: "ReviewSystem", c: "Productivity", b: "Sets up periodic review prompts with templates for weekly and monthly checks.", g: "python-cli" },
  { t: "DecisionLog", c: "Productivity", b: "Logs decisions with context, alternatives and outcomes for later review.", g: "webapp" },
  { t: "DashboardHome", c: "Productivity", b: "A personal start page with links, weather-style widgets and a to-do.", g: "static-site" },
  { t: "ReminderBoard", c: "Productivity", b: "A board of reminders sorted by due date with snooze support.", g: "chrome-extension" },
  { t: "ClipboardNotes", c: "Productivity", b: "Quick-captures clipboard text into organized notes with one keystroke.", g: "chrome-extension" },
  { t: "BragDoc", c: "Productivity", b: "Maintains a running list of accomplishments for reviews and updates.", g: "webapp" },
  { t: "FocusPlaylist", c: "Productivity", b: "Curates background sound loops by focus level from local audio files.", g: "webapp" },
  { t: "StepCounter", c: "Productivity", b: "Logs daily step counts and prints weekly averages and goals.", g: "python-cli" },
  { t: "MarkdownLib", c: "Libraries", b: "A small markdown-to-HTML converter with code blocks and tables.", g: "python-cli" },
  { t: "CSVReaderLib", c: "Libraries", b: "A streaming CSV reader library with type inference and headers.", g: "python-cli" },
  { t: "CLIProgressLib", c: "Libraries", b: "A terminal progress bar and spinner library for scripts.", g: "python-cli" },
  { t: "ColorPrintLib", c: "Libraries", b: "A small library for colored, formatted terminal output.", g: "python-cli" },
  { t: "AsyncQueueLib", c: "Libraries", b: "A Node library for throttled, prioritized async job queues.", g: "node-api" },
  { t: "RetryLib", c: "Libraries", b: "A retry helper with exponential backoff and jitter for calls.", g: "python-cli" },
  { t: "SlugLib", c: "Libraries", b: "A URL slug generator with unicode folding and stopwords.", g: "python-cli" },
  { t: "DateParseLib", c: "Libraries", b: "A forgiving date parser that handles common human formats.", g: "python-cli" },
  { t: "PaginationLib", c: "Libraries", b: "A pagination helper for API results with page and size math.", g: "node-api" },
  { t: "ValidationLib", c: "Libraries", b: "A small validation library with composable rules and messages.", g: "python-cli" },
  { t: "RateLimitLib", c: "Libraries", b: "A sliding-window rate limiter with token bucket options.", g: "node-api" },
  { t: "EventBusLib", c: "Libraries", b: "A typed event bus with wildcard and once subscriptions.", g: "node-api" },
  { t: "HashRingLib", c: "Libraries", b: "A consistent hashing ring for distributing keys across nodes.", g: "python-cli" },
  { t: "TemplateLib", c: "Libraries", b: "A minimal text template engine with loops and conditionals.", g: "python-cli" },
  { t: "QueueLib", c: "Libraries", b: "A persistent job queue with retries and dead-letter handling.", g: "node-api" },
  { t: "CacheLib", c: "Libraries", b: "A TTL cache with LRU eviction and size limits.", g: "python-cli" },
  { t: "LoggerLib", c: "Libraries", b: "A leveled logger with rotating file output and JSON mode.", g: "python-cli" },
  { t: "SemVerLib", c: "Libraries", b: "A semantic version parser and comparator library.", g: "python-cli" },
  { t: "PromisePoolLib", c: "Libraries", b: "Runs async tasks with a concurrency limit and result ordering.", g: "node-api" },
  { t: "ConfigMergeLib", c: "Libraries", b: "Deep-merges layered config files with precedence rules.", g: "python-cli" },
  { t: "ColorPalette", c: "Design/UI", b: "A tool that generates harmonious color palettes from a base color.", g: "static-site" },
  { t: "GradientBuilder", c: "Design/UI", b: "Designs CSS gradients with stops, angles and live previews.", g: "static-site" },
  { t: "TypeScaleTool", c: "Design/UI", b: "Builds typography scales and exports the CSS variables.", g: "static-site" },
  { t: "IconFinder", c: "Design/UI", b: "Searches and downloads icons from a local SVG library.", g: "webapp" },
  { t: "BorderRadiusLab", c: "Design/UI", b: "Tweaks border-radius values with a live box preview.", g: "static-site" },
  { t: "ShadowLab", c: "Design/UI", b: "Designs box shadows with presets and exports the CSS.", g: "static-site" },
  { t: "SpacingScale", c: "Design/UI", b: "Generates spacing scales for design systems from a base unit.", g: "static-site" },
  { t: "MoodBoard", c: "Design/UI", b: "Assembles a visual mood board from color and layout tiles.", g: "static-site" },
  { t: "ContrastCheck", c: "Design/UI", b: "Computes text contrast ratios and flags readability failures.", g: "static-site" },
  { t: "CSSResetGen", c: "Design/UI", b: "Generates a modern CSS reset tuned to your needs.", g: "python-cli" },
  { t: "AvatarGen", c: "Design/UI", b: "Generates avatar images from initials with color variants.", g: "python-cli" },
  { t: "PlaceholderGen", c: "Design/UI", b: "Creates placeholder image files at any size and color.", g: "python-cli" },
  { t: "FontPair", c: "Design/UI", b: "Suggests font pairings and previews them side by side.", g: "static-site" },
  { t: "WireframeKit", c: "Design/UI", b: "A grid of wireframe blocks for sketching page layouts.", g: "static-site" },
  { t: "AccessibilityAudit", c: "Design/UI", b: "Scans an HTML page for common accessibility issues.", g: "python-cli" },
  { t: "SystemInfo", c: "System", b: "Prints OS, CPU, memory and disk details in a readable report.", g: "go-tool" },
  { t: "ProcessWatch", c: "System", b: "Monitors running processes by name and reports CPU and memory use.", g: "python-cli" },
  { t: "DiskSpace", c: "System", b: "Shows disk usage per mounted drive with color-coded warnings.", g: "go-tool" },
  { t: "NetworkSpeed", c: "System", b: "Measures download and upload speeds with a simple report.", g: "python-cli" },
  { t: "MemoryProbe", c: "System", b: "Samples memory usage over time and prints a trend summary.", g: "python-cli" },
  { t: "ClockSync", c: "System", b: "Checks local clock offset against an NTP-style time source.", g: "python-cli" },
  { t: "BatteryReport", c: "System", b: "Reads battery level and charge status from the system.", g: "python-cli" },
  { t: "TempWatch", c: "System", b: "Tracks CPU temperature readings where the system exposes them.", g: "python-cli" },
  { t: "RunLog", c: "System", b: "Logs command executions with timestamps and exit codes.", g: "python-cli" },
  { t: "WakeClock", c: "System", b: "Computes when the machine slept and woke from uptime data.", g: "python-script" },
  { t: "EnvDump", c: "System", b: "Prints the environment in a clean, diff-friendly format.", g: "python-cli" },
  { t: "CpuLoad", c: "System", b: "Samples CPU load averages and prints a small sparkline.", g: "go-tool" },
  { t: "FdCheck", c: "System", b: "Counts open file descriptors per process and flags high use.", g: "python-cli" },
  { t: "UptimeLog", c: "System", b: "Tracks system uptime and reboot history across sessions.", g: "python-script" },
  { t: "MountView", c: "System", b: "Lists mounted filesystems with type, size and mount point.", g: "go-tool" },
  { t: "LandingKit", c: "Static sites", b: "A clean landing page template with hero, features and footer.", g: "static-site" },
  { t: "DocsTheme", c: "Static sites", b: "A documentation theme with a sidebar, search and code blocks.", g: "static-site" },
  { t: "PortfolioOne", c: "Static sites", b: "A single-page portfolio with projects and a contact section.", g: "static-site" },
  { t: "ComingSoon", c: "Static sites", b: "A coming-soon page with a countdown and an email capture form.", g: "static-site" },
  { t: "PricingPage", c: "Static sites", b: "A pricing page with three tiers and a comparison table.", g: "static-site" },
  { t: "BlogTheme", c: "Static sites", b: "A minimal blog theme with a post list and readable article layout.", g: "static-site" },
  { t: "TeamPage", c: "Static sites", b: "A team page with profile cards and a simple grid layout.", g: "static-site" },
  { t: "ErrorPage", c: "Static sites", b: "A friendly 404 page with a search bar and home links.", g: "static-site" },
  { t: "ShowcasePage", c: "Static sites", b: "A product showcase page with screenshots and call-to-action.", g: "static-site" },
  { t: "LandingSplit", c: "Static sites", b: "A split-screen landing page with a form and a feature column.", g: "static-site" },
  { t: "UptimeBot", c: "Bots", b: "A bot that checks service health and posts status updates.", g: "node-bot" },
  { t: "QuoteBot", c: "Bots", b: "A bot that serves random quotes on command with categories.", g: "node-bot" },
  { t: "ReminderBot", c: "Bots", b: "A bot that schedules reminders and nags at the right time.", g: "node-bot" },
  { t: "PollBot", c: "Bots", b: "A bot that creates polls, tallies votes and posts results.", g: "node-bot" },
  { t: "DigestBot", c: "Bots", b: "A bot that posts a daily digest of tracked feeds and events.", g: "node-bot" },
  { t: "TriviaBot", c: "Bots", b: "A bot that runs trivia rounds and keeps a leaderboard.", g: "node-bot" },
  { t: "WeatherBot", c: "Bots", b: "A bot that answers weather queries for a list of cities.", g: "node-bot" },
  { t: "LinkPreviewBot", c: "Bots", b: "A bot that expands shared links into rich previews with titles.", g: "node-bot" },
  { t: "StandupBot", c: "Bots", b: "A bot that collects standup updates and posts a summary.", g: "node-bot" },
  { t: "BirthdayBot", c: "Bots", b: "A bot that remembers birthdays and posts reminders.", g: "node-bot" },
  { t: "StatusBot", c: "Bots", b: "A bot that reports system stats on demand with formatting.", g: "node-bot" },
  { t: "TimerBot", c: "Bots", b: "A bot that runs countdown timers and announces completion.", g: "node-bot" },
  { t: "DictBot", c: "Bots", b: "A bot that defines words and gives usage examples.", g: "node-bot" },
  { t: "FitnessBot", c: "Bots", b: "A bot that logs workouts and posts weekly summaries.", g: "node-bot" },
  { t: "NudgeBot", c: "Bots", b: "A bot that nudges you toward daily habits at set hours.", g: "node-bot" },
  { t: "DeployRig", c: "DevOps", b: "A deployment rig that builds, tests and publishes on tag pushes.", g: "devops-kit" },
  { t: "ConfigGen", c: "DevOps", b: "Generates environment-specific config files from a single template.", g: "python-cli" },
  { t: "HealthProbe", c: "DevOps", b: "A probe service that checks dependencies and reports readiness.", g: "node-api" },
  { t: "ContainerWatch", c: "DevOps", b: "Tails container stats and prints CPU and memory per service.", g: "python-cli" },
  { t: "ComposeLint", c: "DevOps", b: "Validates docker-compose files for common mistakes and missing refs.", g: "python-cli" },
  { t: "EnvMatrix", c: "DevOps", b: "Runs a matrix of environment combinations and reports pass rates.", g: "python-script" },
  { t: "SlaClock", c: "DevOps", b: "Tracks uptime against an SLA target and predicts breach risk.", g: "python-cli" },
  { t: "RolloutCheck", c: "DevOps", b: "Verifies a rolling deploy by sampling responses and flagging errors.", g: "python-cli" },
  { t: "RegistryClean", c: "DevOps", b: "Lists old container image tags and proposes safe cleanup batches.", g: "python-cli" },
  { t: "PipelineBoard", c: "DevOps", b: "A dashboard that visualizes pipeline runs and their durations.", g: "react-app" }
];
