// 365 catalog - chunk 3: Data, AI/ML, Security, Games
module.exports = [
  { t: "CSVFilter", c: "Data", b: "Filters and transforms CSV files with a small pipe-style query language.", g: "python-cli" },
  { t: "DataValidator", c: "Data", b: "Validates rows against a schema and prints a report of violations.", g: "python-cli" },
  { t: "TableSummary", c: "Data", b: "Prints column statistics for a dataset: counts, nulls, min, max and averages.", g: "python-pipeline" },
  { t: "JSONToTable", c: "Data", b: "Flattens nested JSON documents into rows and writes them to CSV or SQLite.", g: "python-pipeline" },
  { t: "Deduper", c: "Data", b: "Finds and removes duplicate rows using fuzzy key matching.", g: "python-cli" },
  { t: "TimeSeriesGap", c: "Data", b: "Detects gaps and outliers in time-series data and reports the windows.", g: "python-cli" },
  { t: "TextCluster", c: "Data", b: "Groups short text records into clusters by shared words and prints the groups.", g: "python-pipeline" },
  { t: "LogParser", c: "Data", b: "Parses common log formats into structured rows for filtering and aggregation.", g: "python-pipeline" },
  { t: "CSVJoiner", c: "Data", b: "Joins two CSV files on a key column and writes a merged output.", g: "python-cli" },
  { t: "DataSample", c: "Data", b: "Draws stratified or random samples from a dataset with a stable seed.", g: "python-cli" },
  { t: "HistogramTool", c: "Data", b: "Renders ASCII histograms for numeric columns directly in the terminal.", g: "python-cli" },
  { t: "SchemaDiff", c: "Data", b: "Compares two dataset schemas and lists added, removed or changed fields.", g: "python-cli" },
  { t: "AnomalyScan", c: "Data", b: "Scores rows for unusual values using z-scores and flags the worst offenders.", g: "python-pipeline" },
  { t: "SQLiteToCSV", c: "Data", b: "Exports SQLite tables to CSV with type handling and progress output.", g: "python-cli" },
  { t: "GeoBounds", c: "Data", b: "Computes bounding boxes and centroid stats for coordinate datasets.", g: "python-cli" },
  { t: "WordFreq", c: "Data", b: "Counts word frequency in text files and prints a ranked list.", g: "python-cli" },
  { t: "DateNormalizer", c: "Data", b: "Converts mixed date formats in a dataset to one canonical format.", g: "python-pipeline" },
  { t: "MergePipeline", c: "Data", b: "Runs a merge of several source files into one clean dataset with dedup.", g: "python-pipeline" },
  { t: "EncodingDetect", c: "Data", b: "Detects text file encodings and converts them to UTF-8 in bulk.", g: "python-cli" },
  { t: "DataGenKit", c: "Data", b: "Generates realistic-looking sample datasets from field type definitions.", g: "python-cli" },
  { t: "Tokenizer", c: "AI/ML", b: "Splits text into tokens with configurable rules and prints the token stream.", g: "python-cli" },
  { t: "EmbeddingCache", c: "AI/ML", b: "Caches embedding lookups locally with a simple vector store.", g: "python-cli" },
  { t: "PromptBench", c: "AI/ML", b: "Runs prompt variants against a model API and ranks the outputs.", g: "python-cli" },
  { t: "VectorSearch", c: "AI/ML", b: "Indexes text with embeddings and searches by similarity from the CLI.", g: "python-cli" },
  { t: "ImageClassifier", c: "AI/ML", b: "Classifies images in a folder using a lightweight pretrained-style pipeline.", g: "python-pipeline" },
  { t: "SentimentLabel", c: "AI/ML", b: "Scores short texts as positive, negative or neutral and prints a summary.", g: "python-cli" },
  { t: "TextSummarizer", c: "AI/ML", b: "Compresses long documents into bullet summaries using extractive methods.", g: "python-pipeline" },
  { t: "CsvClassifier", c: "AI/ML", b: "Trains a small classifier on labeled CSV rows and evaluates its accuracy.", g: "python-cli" },
  { t: "KeywordExtract", c: "AI/ML", b: "Extracts the top keywords from documents and ranks them by relevance.", g: "python-cli" },
  { t: "DedupEmbeddings", c: "AI/ML", b: "Finds near-duplicate documents using embedding similarity.", g: "python-pipeline" },
  { t: "ModelCardGen", c: "AI/ML", b: "Generates a model card markdown from evaluation results.", g: "python-script" },
  { t: "DataLabeler", c: "AI/ML", b: "Walks through unlabeled rows and saves labels to a JSON file.", g: "python-cli" },
  { t: "FeatureScale", c: "AI/ML", b: "Normalizes numeric columns for machine learning and reports the transforms.", g: "python-cli" },
  { t: "ConfusionDraw", c: "AI/ML", b: "Renders a confusion matrix from a predictions file as an ASCII table.", g: "python-cli" },
  { t: "Splitter", c: "AI/ML", b: "Splits datasets into train, validation and test sets with balanced classes.", g: "python-cli" },
  { t: "PromptFolder", c: "AI/ML", b: "Organizes prompts into versioned folders with metadata and exports.", g: "python-cli" },
  { t: "TextCloak", c: "AI/ML", b: "Anonymizes names and identifiers in text before sharing or training.", g: "python-pipeline" },
  { t: "VocabularyBuilder", c: "AI/ML", b: "Builds a vocabulary file from a corpus with frequency cutoffs.", g: "python-pipeline" },
  { t: "LossCurvePlot", c: "AI/ML", b: "Plots training curves from log files as an ASCII chart.", g: "python-cli" },
  { t: "InferenceRunner", c: "AI/ML", b: "Runs batch inference through a model endpoint and stores results to a file.", g: "python-cli" },
  { t: "PortScanner", c: "Security", b: "Scans a host for open ports and reports service banners.", g: "python-cli" },
  { t: "HashCompare", c: "Security", b: "Verifies file checksums against expected values and reports mismatches.", g: "go-tool" },
  { t: "CipherLab", c: "Security", b: "Encrypts and decrypts files with multiple ciphers from the command line.", g: "python-cli" },
  { t: "PassphraseGen", c: "Security", b: "Generates strong passphrases with configurable word counts and separators.", g: "python-cli" },
  { t: "LogAudit", c: "Security", b: "Scans auth logs for failed attempts and flags unusual login patterns.", g: "python-pipeline" },
  { t: "ChecksumTree", c: "Security", b: "Builds a manifest of hashes for every file in a directory tree.", g: "go-tool" },
  { t: "CertViewer", c: "Security", b: "Inspects TLS certificate details and expiration dates from a host.", g: "python-cli" },
  { t: "PermissionAudit", c: "Security", b: "Finds files with risky permissions in a tree and prints recommendations.", g: "python-cli" },
  { t: "DependencyCVE", c: "Security", b: "Cross-checks dependency versions against a local advisory list.", g: "python-cli" },
  { t: "PasswordHealth", c: "Security", b: "Scores password strength with detailed feedback on weak patterns.", g: "python-cli" },
  { t: "SessionInspector", c: "Security", b: "Parses and displays cookie and session token details from a file.", g: "python-cli" },
  { t: "NetworkScan", c: "Security", b: "Lists active hosts on a local subnet and their open ports.", g: "python-cli" },
  { t: "CipherSuiteList", c: "Security", b: "Connects to a TLS endpoint and lists supported cipher suites.", g: "python-cli" },
  { t: "MalwarePattern", c: "Security", b: "Scans files for suspicious byte patterns and prints matches with context.", g: "python-cli" },
  { t: "TwoFactorTotp", c: "Security", b: "Generates and verifies TOTP codes for local 2FA testing.", g: "python-cli" },
  { t: "KeyGenKit", c: "Security", b: "Generates and manages local key pairs for signing operations.", g: "python-cli" },
  { t: "HeaderScan", c: "Security", b: "Checks a website's response headers against a security best-practice list.", g: "python-cli" },
  { t: "FileIntegrity", c: "Security", b: "Monitors a directory for unauthorized file changes using hashes.", g: "python-cli" },
  { t: "BannerGrab", c: "Security", b: "Fetches service banners from a host and matches them against known versions.", g: "python-cli" },
  { t: "SaltCheck", c: "Security", b: "Verifies that passwords are stored with unique salts in a sample database.", g: "python-cli" },
  { t: "SnakeGame", c: "Games", b: "A terminal snake game with levels, speed-up and a high-score file.", g: "python-cli" },
  { t: "TicTacToe", c: "Games", b: "A tic-tac-toe game with a simple unbeatable AI opponent.", g: "python-cli" },
  { t: "WordGuess", c: "Games", b: "A word guessing game with a word bank and letter feedback.", g: "python-cli" },
  { t: "MemoryMatch", c: "Games", b: "A card-matching memory game played in the terminal.", g: "python-cli" },
  { t: "NumberGuess", c: "Games", b: "A number guessing game with scoring and attempt limits.", g: "python-cli" },
  { t: "Minesweeper", c: "Games", b: "A terminal minesweeper with configurable board size and difficulty.", g: "python-cli" },
  { t: "Hangman", c: "Games", b: "A hangman game with a word list and guessed-letter tracking.", g: "python-cli" },
  { t: "ConnectFour", c: "Games", b: "A connect four game against a simple AI that blocks threats.", g: "python-cli" },
  { t: "SimonSays", c: "Games", b: "A memory sequence game that grows with each correct round.", g: "python-cli" },
  { t: "RockPaperScissors", c: "Games", b: "A rock-paper-scissors game with score tracking and best-of rounds.", g: "python-cli" },
  { t: "BlackjackCLI", c: "Games", b: "A blackjack game with betting, a deck and basic strategy hints.", g: "python-cli" },
  { t: "SudokuSolver", c: "Games", b: "Solves Sudoku puzzles from text input and prints the solution.", g: "python-cli" },
  { t: "2048Terminal", c: "Games", b: "A 2048 clone playable in the terminal with arrow key input.", g: "python-cli" },
  { t: "TriviaQuiz", c: "Games", b: "A trivia quiz with categories, scoring and a question bank.", g: "python-cli" },
  { t: "Battleship", c: "Games", b: "A battleship game with a hidden board and coordinate guessing.", g: "python-cli" },
  { t: "Mastermind", c: "Games", b: "A code-breaking game with peg feedback and limited guesses.", g: "python-cli" },
  { t: "QuizFlash", c: "Games", b: "A spaced-repetition flashcard quiz with confidence ratings.", g: "python-cli" },
  { t: "DicePoker", c: "Games", b: "A dice poker game with rerolls and hand rankings.", g: "python-cli" },
  { t: "PongWeb", c: "Games", b: "A two-player pong game in the browser with score display.", g: "static-site" },
  { t: "ReactionTime", c: "Games", b: "A reaction-time tester that measures and averages your clicks.", g: "static-site" }
];
